# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='restaurant_data.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15restaurant_data.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x14\n\x05Shops\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"\x8d\x01\n\x07GeoHash\x12\x11\n\tprecision\x18\x01 \x01(\x05\x12$\n\x06lookup\x18\x02 \x03(\x0b\x32\x14.GeoHash.LookupEntry\x1aI\n\x0bLookupEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.ListValue:\x02\x38\x01\"\x94\x01\n\x0eRestaurantData\x12\x46\n\x10time_slot_lookup\x18\x01 \x03(\x0b\x32\x1a.google.protobuf.ListValueR\x10time_slot_lookup\x12$\n\x08geo_hash\x18\x02 \x01(\x0b\x32\x08.GeoHashR\x08geo_hash\x12\x14\n\x05shops\x18\x03 \x03(\x0b\x32\x05.Shop\"$\n\x08Position\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lng\x18\x02 \x01(\x02\"\xd1\x01\n\x04Shop\x12%\n\x08position\x18\x01 \x01(\x0b\x32\t.PositionR\x08position\x12\x1c\n\tpost_code\x18\x02 \x01(\tR\tpost_code\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x46\n\x10half_price_times\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.ListValueR\x10half_price_times\x12(\n\x0fnearest_station\x18\x05 \x01(\tR\x0fnearest_stationb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_SHOPS = _descriptor.Descriptor(
  name='Shops',
  full_name='Shops',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='Shops.ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=75,
)


_GEOHASH_LOOKUPENTRY = _descriptor.Descriptor(
  name='LookupEntry',
  full_name='GeoHash.LookupEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GeoHash.LookupEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='GeoHash.LookupEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=219,
)

_GEOHASH = _descriptor.Descriptor(
  name='GeoHash',
  full_name='GeoHash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='precision', full_name='GeoHash.precision', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lookup', full_name='GeoHash.lookup', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GEOHASH_LOOKUPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=219,
)


_RESTAURANTDATA = _descriptor.Descriptor(
  name='RestaurantData',
  full_name='RestaurantData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_slot_lookup', full_name='RestaurantData.time_slot_lookup', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='time_slot_lookup', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geo_hash', full_name='RestaurantData.geo_hash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='geo_hash', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shops', full_name='RestaurantData.shops', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=370,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='Position.lat', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='Position.lng', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=408,
)


_SHOP = _descriptor.Descriptor(
  name='Shop',
  full_name='Shop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='Shop.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='position', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_code', full_name='Shop.post_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='post_code', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Shop.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='half_price_times', full_name='Shop.half_price_times', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='half_price_times', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nearest_station', full_name='Shop.nearest_station', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='nearest_station', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=620,
)

_GEOHASH_LOOKUPENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
_GEOHASH_LOOKUPENTRY.containing_type = _GEOHASH
_GEOHASH.fields_by_name['lookup'].message_type = _GEOHASH_LOOKUPENTRY
_RESTAURANTDATA.fields_by_name['time_slot_lookup'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
_RESTAURANTDATA.fields_by_name['geo_hash'].message_type = _GEOHASH
_RESTAURANTDATA.fields_by_name['shops'].message_type = _SHOP
_SHOP.fields_by_name['position'].message_type = _POSITION
_SHOP.fields_by_name['half_price_times'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
DESCRIPTOR.message_types_by_name['Shops'] = _SHOPS
DESCRIPTOR.message_types_by_name['GeoHash'] = _GEOHASH
DESCRIPTOR.message_types_by_name['RestaurantData'] = _RESTAURANTDATA
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Shop'] = _SHOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Shops = _reflection.GeneratedProtocolMessageType('Shops', (_message.Message,), dict(
  DESCRIPTOR = _SHOPS,
  __module__ = 'restaurant_data_pb2'
  # @@protoc_insertion_point(class_scope:Shops)
  ))
_sym_db.RegisterMessage(Shops)

GeoHash = _reflection.GeneratedProtocolMessageType('GeoHash', (_message.Message,), dict(

  LookupEntry = _reflection.GeneratedProtocolMessageType('LookupEntry', (_message.Message,), dict(
    DESCRIPTOR = _GEOHASH_LOOKUPENTRY,
    __module__ = 'restaurant_data_pb2'
    # @@protoc_insertion_point(class_scope:GeoHash.LookupEntry)
    ))
  ,
  DESCRIPTOR = _GEOHASH,
  __module__ = 'restaurant_data_pb2'
  # @@protoc_insertion_point(class_scope:GeoHash)
  ))
_sym_db.RegisterMessage(GeoHash)
_sym_db.RegisterMessage(GeoHash.LookupEntry)

RestaurantData = _reflection.GeneratedProtocolMessageType('RestaurantData', (_message.Message,), dict(
  DESCRIPTOR = _RESTAURANTDATA,
  __module__ = 'restaurant_data_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantData)
  ))
_sym_db.RegisterMessage(RestaurantData)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'restaurant_data_pb2'
  # @@protoc_insertion_point(class_scope:Position)
  ))
_sym_db.RegisterMessage(Position)

Shop = _reflection.GeneratedProtocolMessageType('Shop', (_message.Message,), dict(
  DESCRIPTOR = _SHOP,
  __module__ = 'restaurant_data_pb2'
  # @@protoc_insertion_point(class_scope:Shop)
  ))
_sym_db.RegisterMessage(Shop)


_GEOHASH_LOOKUPENTRY.has_options = True
_GEOHASH_LOOKUPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
